<a href="https://colab.research.google.com/github/DimaBU777/dap-2024/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<3>  <12002208> <Бурдюжа Д.А.>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'1.26.4'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [1]:
import numpy as np
array = np.random.randint(1, 100, (10, 10))
print("\nСозданный массив: \n\n", array)
print("\nМинимальное значение:", array.min())
print("Максимальное значение:", array.max())


Созданный массив: 

 [[59 27 28 57 79 73 76  3 22 93]
 [ 8 68  2  9 48 76 97 46 99 60]
 [77 62 59 14 75 41 65 99 42 83]
 [14 43 85  8 76 87 75 45 44 90]
 [28  5 42 75 83 33 95 54 71 81]
 [92 34 37 48 94 94  2 79 41 68]
 [84 78 45 97 62 88 42 66 90  7]
 [75 82 35 31 66 55 11 28 82 47]
 [16 63 57 72 91 66 16 19 98 32]
 [53  9 12 21 78 98 14 44 21 85]]

Минимальное значение: 2
Максимальное значение: 99


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [2]:
import numpy as np
matrix = np.zeros((8,8))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print("Матрица 8х8 в шахматном порядке: \n", matrix)

Матрица 8х8 в шахматном порядке: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [3]:
import numpy as np
x = np.arange(11)
print("Исходный массив:\n", x)
x[(x > 3) & (x < 8)] *= -1
print("\nИзмененный массив:\n", x)

Исходный массив:
 [ 0  1  2  3  4  5  6  7  8  9 10]

Измененный массив:
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [4]:
import numpy as np
z = np.random.rand(5, 10)
print("Матрица: \n", z)
means = np.mean(z, axis=1, keepdims=True)
z[:, :9] -= means
print("\nСреднее значение:\n", means)
print("\nИзмененная матрица:\n", z)

Матрица: 
 [[0.94901512 0.48443253 0.40784079 0.27831017 0.07771674 0.29141087
  0.06292453 0.69145783 0.07575932 0.51032328]
 [0.31991945 0.19483834 0.72092532 0.99358383 0.76777425 0.44649449
  0.96340301 0.9695401  0.78843838 0.91622103]
 [0.94086494 0.18244498 0.35308169 0.73529072 0.87831997 0.6556202
  0.00216404 0.58190924 0.29344244 0.9816847 ]
 [0.10474995 0.32263447 0.69576529 0.34257619 0.92314874 0.01942821
  0.70913202 0.35467842 0.80708462 0.73398539]
 [0.82590527 0.47972053 0.27246508 0.1571777  0.63492847 0.27987315
  0.78183527 0.50080524 0.88024844 0.13923867]]

Среднее значение:
 [[0.38291912]
 [0.70811382]
 [0.56048229]
 [0.50131833]
 [0.49521978]]

Измененная матрица:
 [[ 0.566096    0.10151341  0.02492167 -0.10460895 -0.30520238 -0.09150825
  -0.31999458  0.30853871 -0.3071598   0.51032328]
 [-0.38819437 -0.51327548  0.0128115   0.28547001  0.05966043 -0.26161933
   0.25528919  0.26142628  0.08032456  0.91622103]
 [ 0.38038265 -0.37803731 -0.2074006   0.17480843  

5. Поменяйте 1 и 2 строки матрицы

In [5]:
import numpy as np
z = np.arange(25).reshape(5,5)
print("Матрица:\n", z)
z[[1, 2]] = z[[2, 1]]
print("\nИзмененная матрица:\n", z)

Матрица:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Измененная матрица:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [6]:
import numpy as np
z = np.random.random((10, 2))
print("Декартова система координат:\n", z)
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
phi = np.arctan2(y, x)
pz = np.column_stack((r, phi))
print("\nПолярные координаты:\n", pz)

Декартова система координат:
 [[0.44683091 0.43521433]
 [0.10764358 0.88954515]
 [0.43931368 0.07591341]
 [0.12426513 0.12746822]
 [0.09921533 0.68858206]
 [0.02610981 0.80878166]
 [0.89973043 0.66253549]
 [0.93598331 0.84746053]
 [0.69632287 0.20383675]
 [0.43091189 0.61401037]]

Полярные координаты:
 [[0.62375426 0.77222887]
 [0.89603444 1.45037216]
 [0.44582435 0.17111025]
 [0.17801677 0.79812159]
 [0.69569313 1.42769478]
 [0.809203   1.53852465]
 [1.1173487  0.6347214 ]
 [1.26263776 0.735803  ]
 [0.7255446  0.28477665]
 [0.75012918 0.95886397]]


7. Заменить максимальный элемент массива на ноль

In [7]:
import numpy as np
z = np.random.random(10)
print("Массив:\n", z)
max = np.argmax(z)
print("\nИндекс максимального элемента:", max)
z[max] = 0
print("\nИзмененный массив:\n", z)

Массив:
 [0.5177946  0.38798395 0.50225519 0.39739594 0.51114838 0.7057542
 0.16850762 0.28369031 0.32296986 0.16953792]

Индекс максимального элемента: 5

Измененный массив:
 [0.5177946  0.38798395 0.50225519 0.39739594 0.51114838 0.
 0.16850762 0.28369031 0.32296986 0.16953792]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [8]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print("Массив:\n", z)
print("\nМассив индексов:\n", i)
unique = np.unique(i)
z[unique] += 1
print("\nИзмененный массив:\n", z)

Массив:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Массив индексов:
 [1 9 8 7 4 2 7 1 4 4 9 6 0 7 8 5 6 4 5 2]

Измененный массив:
 [2. 2. 2. 1. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [9]:
import numpy as np
z = np.array([1,2,3,4,5])
print("Вектор:\n", z)
x = np.zeros(len(z) + (len(z) - 1) * 3)
x[::4] = z
print("\nНовый вектор:\n", x)

Вектор:
 [1 2 3 4 5]

Новый вектор:
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [10]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0,100)
print("Массив:\n", z)
print("\nЗаданное значение:", v)
x = np.fabs(z - v).argmin()
y = z[x]
print("\nБлижайшее значение для", v, "=", y)

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Заданное значение: 60.64288271322026

Ближайшее значение для 60.64288271322026 = 61
