<a href="https://colab.research.google.com/github/DimaBU777/dap-2024/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Создание массива 10x10 со случайными значениями
array = np.random.rand(10, 10)  # Значения в диапазоне [0, 1]

# Поиск минимума и максимума
min_value = np.min(array)
max_value = np.max(array)

print("Массив:\n", array)
print("Минимальное значение:", min_value)
print("Максимальное значение:", max_value)


Массив:
 [[0.44168947 0.7900813  0.3684044  0.47309496 0.06895944 0.17624727
  0.63297653 0.73596555 0.17022217 0.54576377]
 [0.37751027 0.67440797 0.28454106 0.77158902 0.88535929 0.43416681
  0.53489742 0.07360551 0.47403134 0.36688777]
 [0.04714808 0.18068977 0.41942306 0.79157689 0.4561053  0.08212505
  0.20022908 0.92491375 0.3068302  0.29379815]
 [0.86887132 0.2896357  0.7730572  0.69564567 0.36830331 0.15432818
  0.16949286 0.52349262 0.62477809 0.96720372]
 [0.84325179 0.36718059 0.66367558 0.88564431 0.41259131 0.87262653
  0.51672864 0.70377578 0.06985946 0.50054714]
 [0.93760481 0.42558944 0.35524711 0.09740499 0.57345255 0.0497222
  0.94744062 0.19363804 0.32689907 0.38303352]
 [0.62758645 0.13593529 0.67859587 0.12569097 0.46110045 0.52503331
  0.07233075 0.61847883 0.7714215  0.41669214]
 [0.03250732 0.38935389 0.03318349 0.02332328 0.57753405 0.90396483
  0.88505517 0.52774182 0.06268669 0.83271613]
 [0.20671924 0.04620369 0.25202056 0.46211875 0.06686492 0.18703017
  0.

In [ ]:
import numpy as np

# Создание матрицы 8x8
chessboard = np.zeros((8, 8), dtype=int)

# Заполнение в шахматном порядке
chessboard[1::2, ::2] = 1  # Четные строки, нечетные столбцы
chessboard[::2, 1::2] = 1  # Нечетные строки, четные столбцы

print(chessboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np

z = np.arange(11)

# Поменять знак у элементов, значения которых между 3 и 8
z[(z > 3) & (z < 8)] *= -1

print(z)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
import numpy as np

z = np.random.rand(5, 10)

# Находим среднее значение для каждой строки
mean_values = np.mean(z, axis=1)

# Вычитаем среднее значение из каждого элемента строки
z = z - mean_values[:, np.newaxis]

print(z)


[[-0.22883014 -0.25873955  0.16508241  0.27097381  0.20536428  0.26536113
  -0.47920863 -0.15893693  0.40789206 -0.18895843]
 [ 0.32930003  0.17495607  0.46010188  0.08536591 -0.12107314 -0.16136088
  -0.26198628 -0.30296973  0.01495045 -0.2172843 ]
 [-0.31193382  0.55746396  0.09376055  0.13148512 -0.07456228 -0.24652698
  -0.00162181 -0.3306354  -0.33784546  0.52041611]
 [-0.3223921   0.37294319 -0.00138639 -0.3206543   0.17316446  0.31206288
   0.00074206 -0.10331177  0.07792526 -0.18909328]
 [-0.29204463  0.42253529  0.31098001 -0.1270647   0.0589932   0.28537596
   0.24876595 -0.39475909 -0.19368647 -0.31909553]]


In [ ]:
import numpy as np

z = np.arange(25).reshape(5, 5)

# Поменять 1 и 2 строки местами
z[[0, 1]] = z[[1, 0]]

print(z)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
import numpy as np

z = np.random.random((10, 2))

# Преобразуем в полярную систему координат
r = np.sqrt(z[:, 0]**2 + z[:, 1]**2)  # Радиус
theta = np.arctan2(z[:, 1], z[:, 0])  # Угол

# Результат
polar_coordinates = np.column_stack((r, theta))

print(polar_coordinates)


[[0.83269809 0.11420047]
 [0.80268729 0.30874985]
 [0.51530239 0.57311304]
 [0.48249752 0.40991515]
 [0.94702532 1.10330961]
 [1.00355513 0.4106645 ]
 [1.24431467 0.80671587]
 [0.47569647 0.95891641]
 [0.55616136 0.02022686]
 [0.49098407 0.4718913 ]]


In [ ]:
import numpy as np

z = np.random.random(10)

# Заменить максимальный элемент на ноль
z[np.argmax(z)] = 0

print(z)


[0.54004565 0.         0.50635826 0.14500532 0.61118504 0.4577366
 0.00803569 0.18892493 0.05587851 0.65812839]


In [ ]:
import numpy as np

z = np.ones(10)
i = np.random.randint(0, len(z), 20)

# Добавление 1 к каждому элементу с индексом, заданным в массиве i (добавление только 1 раз)
unique_indices = np.unique(i)  # Убираем повторяющиеся индексы
z[unique_indices] += 1

print(z)


[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [ ]:
import numpy as np

z = np.array([1, 2, 3, 4, 5])

# Создаем новый вектор с тремя нулями между каждым элементом
new_vector = np.zeros(len(z) * 4 - 3, dtype=int)

# Заполняем новый вектор значениями из z с тремя нулями между каждым элементом
new_vector[::4] = z

print(new_vector)



[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [ ]:
import numpy as np

z = np.arange(100)  # Массив от 0 до 99
v = np.random.uniform(0, 100)  # Случайное число от 0 до 100

# Находим ближайшее число в массиве z к числу v
closest_value = z[np.abs(z - v).argmin()]

print(f"Заданное значение: {v}")
print(f"Ближайшее значение в массиве: {closest_value}")


Заданное значение: 19.342318353968967
Ближайшее значение в массиве: 19
